const data2 = [
    {
    id: 1,
    slug: "bond-hearings-and-appeals",
    img: "/criminal-offenses/4.jpg",
    title: "Bond Hearing and Appeals",
    dis1: "The lawyers at 757 Defense recognize that being arrested and figuring out if you will be released on a criminal offense can be highly confusing. You may need to sign bond paperwork or have somebody come and bail you out before you can be removed, pending your appeal.",
    dis2: "Our Virginia appeals lawyer thoroughly knows the bond hearing and appeals process in Virginia. We will help and provide you with the information, support, and resources you need.",
  },
  {
    id: 2,
    slug: "criminal-discovery",
    img: "/criminal-offenses/4.jpg",
    title: "Criminal Discovery",
    dis1: "Criminal Discovery is a process whereby a criminal defendant finds out what evidence the prosecution and law enforcement have against them. Discovery in a criminal case must be assessed on a case-by-case basis. Discovery needs to be reviewed carefully to determine if anything is missing.",
    dis2: "Our attorneys at 757 Defense analyze discovery multiple times to ensure no stone is left unturned. As a result, we have had considerable success obtaining discovery through the court that the prosecution initially refused to provide.",
  },
  {
    id: 3,
    slug: "evidentiary-motion",
    img: "/criminal-offenses/4.jpg",
    title: "Evidentiary Motion",
    dis1: "The motion to strike out evidence in Virginia may be directed against a specific item of evidence, the testimony of a particular witness, or it may be used to strike every piece of evidence. Winning such a motion to strike is genuinely achieving.",
    dis2: "At 757 Defense, our Virginia Beach criminal defense lawyers pursue your best defense for succeeding against felony, misdemeanor, DUI prosecutions, and protective order proceedings.",
  },
  {
    id: 4,
    slug: "motions-to-suppress-the-evidence",
    img: "/criminal-offenses/4.jpg",
    title: "Motions to suppress the evidence",
    dis1: "A motion to suppress evidence is when attorneys challenge the constitution or some aspects of the police investigation. If the court agrees that there was a constitutional violation in the investigation, evidence obtained after that is suppressed.",
    dis2: "Our experienced defense attorneys at 757 Defense know how to suppress evidence collected illegally or otherwise inadmissible.",
  },
  {
    id: 5,
    slug: "preliminary-hearing",
    img: "/criminal-offenses/4.jpg",
    title: "Preliminary Hearing",
    dis1: "In felony cases, a preliminary hearing is conducted after the arrest and bail hearing. The preliminary hearing determines if there is probable cause to believe that the person has committed the crime with which they are charged. If probable is found, then the case is sent to the Grand Jury.",
    dis2: "Our experienced criminal defense lawyers can give representation immediately if you have an upcoming preliminary hearing. We have successfully moved for the dismissal of entire cases and some of the most severe charges on numerous occasions.",
  },
  {
    id: 6,
    slug: "probation-hearing",
    img: "/criminal-offenses/4.jpg",
    title: "Probation Hearing",
    dis1: "Violating the terms of your probation can be a grave matter. Depending upon the circumstances of your case, you may face harsh criminal penalties and even run the risk of being imprisoned.",
    dis2: "757 Defense’s Virginia Beach criminal defense lawyers, know what it takes to confront a probation violation allegation successfully. If you have already been summoned for a probation hearing, our criminal defense attorney will help you build the most robust possible defense against the accusations.",
  },
  {
    id: 7,
    slug: "bench-and-jury-trials",
    img: "/criminal-offenses/4.jpg",
    title: "Bench and Jury Trials",
    dis1: "Cases not resolved through a plea agreement are set for trial. Trials will be decided either by a judge in a bench trial or by a jury.",
    dis2: "Our skilled trial attorneys have handled countless bench and a jury trial on various legal disputes. We provide vigorous representation in the courtroom, drawing on our extensive experience and understanding of the law to give our clients the best chance of success under the circumstances of each case.",
  },
]
export default data2;