const data = [
  {
    id: 1,
    slug: "assault-and-battery",
    img: "/criminal-offenses/1.jpg",
    title: "Assault and Battery",
    dis1: "Assault and battery are among the most common violent crime charges defendants face. And as with most violent crimes, the possible consequences of a conviction for assault and battery are usually significant.",
    dis2: "At 757 Defense, our Virginia Beach criminal defense attorneys recognize the seriousness of any violent crime charge. Furthermore, our lawyers believe passionately in the cause of providing the best possible legal representation for our clients.",
  },
  {
    id: 2,
    slug: "drug-crimes",
    img: "https://images.pexels.com/photos/7231226/pexels-photo-7231226.jpeg",
    title: "Drug Crimes",
    dis1: "If you are charged with a drug crime in Virginia, you could face significant penalties, especially if you have been convicted of a similar charge.",
    dis2: "At 757 Defense, our Virginia Beach criminal defense lawyers will counter those charges with more than experience but an aggressive approach to delivering dynamic legal solutions so that you can confidently proceed with your life.",
  },
  {
    id: 3,
    slug: "theft-property-crimes",
    img: "/criminal-offenses/2.jpg",
    title: "Theft/ Property Crimes",
    dis1: "You may face severe consequences and repercussions if you have been charged or arrested for theft or property offenses (criminal mischief or vandalism) in Virginia Beach.",
    dis2: "757 Defense specializes in criminal law, and we have extensive experience defending people charged with property or theft offenses. We will provide detailed and in-depth advice at any stage if you face these charges.",
  },
  {
    id: 4,
    slug: "violent-offenses",
    img: "/criminal-offenses/2.jpg",
    title: "Violent Offenses",
    dis1: "Violent crime comprises a range of offenses, from common assault to murder. It also includes using weapons such as firearms, knives, and corrosive substances like acid. Individuals charged with these offenses need an attorney.",
    dis2: "You will want to select a criminal defense lawyer experienced in these cases. At 757 Defense, we have highly qualified and knowledgeable lawyers to guide your case throughout the legal process.",
  },
  {
    id: 5,
    slug: "weapons-firearms",
    img: "https://images.pexels.com/photos/15264967/pexels-photo-15264967.jpeg",
    title: "Weapons/ Firearms",
    dis1: "In the context of criminal charges, a weapon is anything used to threaten or hurt a person and the use or possession of firearms.",
    dis2: "757 Defense specializes in criminal law and has extensive experience defending people charged with Weapons/ Firearms offenses. We will provide careful and detailed advice at any stage if you face these charges.",
  },
  {
    id: 6,
    slug: "domestic-violence",
    img: "/criminal-offenses/2.jpg",
    title: "Domestic Violence",
    dis1: "If you have been charged with domestic violence, you may face serious consequences. For example, domestic assault in Virginia is punished with jail, fines, and the inability to possess a firearm. There could also be employment and immigration consequences.",
    dis2: "At 757 Defense, our Virginia Beach criminal defense lawyers will help you build a proper defense.",
  },
  {
    id: 7,
    slug: "protective-orders",
    img: "/criminal-offenses/2.jpg",
    title: "Protective Orders",
    dis1: "It is a severe crime to violate a civil protective order in Virginia. You can be charged with a separate criminal offense if you have been accused of violating a protective order.",
    dis2: "At 757 Defense, we can help you build a strong defense and ensure no protective order violations occur.",
  },
  {
    id: 8,
    slug: "juvenile-offense",
    img: "/criminal-offenses/4.jpg",
    title: "Juvenile Offense",
    dis1: "Juvenile offenses are handled differently than if they were prosecuted as adults in Virginia. The primary focus remains on rehabilitation rather than punishing them. However, in case of a serious felony offense, they can be tried as adults and face harsh penalties.",
    dis2: "At 757 Defense, our Virginia Beach criminal defense lawyersunderstandthat children need a skilled attorney to face the court on their behalf.",
  },
];
export default data;